name: Hello World Workflow
on:
  push:
    branches:
      - main
    paths:
      ".github/workflows/cicd.yml"

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello, world!"
